### ISSUE TITLE
Order Summary in Cart block crashes when used along with WooCommerce Pre-Orders

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-blocks#10344]
### Background

When WooCommerce Pre-Orders extension is enabled, then Order Summary in Cart block crashes with the error in console in Editor:

```
react-dom.min.js?ver=18:1 TypeError: Cannot read properties of undefined (reading 'charged_upfront')
    at index.js?ver=8615f6ce77cd241f630df36faabb09c2:1:922
    at totalLabel (index.js?ver=8615f6ce77cd241f630df36faabb09c2:1:997)
    at index.ts:230:21
    at Array.forEach (<anonymous>)
    at applyCheckoutFilter (index.ts:228:10)
    at TotalsFooterItem (index.tsx:64:35)
    at St (react-dom.min.js?ver=18:1:47627)
    at $s (react-dom.min.js?ver=18:1:120574)
    at Sl (react-dom.min.js?ver=18:1:88649)
    at kl (react-dom.min.js?ver=18:1:88577)
```

<img width="1155" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/20098064/ffebe40e-1388-429f-87b7-64fdaf1141bc">

Disabling the extension is enough to make Order Summary work normally.

### Steps to reproduce

1. Install WooCommerce Pre-Orders
2. Go to Editor or create new post
3. Add Cart block
4. You should see a broken Order Summary block

**Comment by mikejolley** [comment]
Thanks for reporting @kmanijak. It looks like pre-orders uses a filter than runs on the frontend and editor, but doens't check to see if the properties exist before accessing them. See:

https://github.com/woocommerce/woocommerce-pre-orders/blob/35abfa71e9d652196a78d50323b4c863230415d8/src/index.js#L22-L30

I think this needs to be resolved in Pre-Orders so I will move it across, but I am also cc'ing @ralucaStan and @senadir for awareness, as this is a case where perhaps filters could be wrapped in some kind of error handling to prevent this breaking editor views.
